### PR TITLE
108 turn time

### LINKED ISSUE #108: Turn based time system
A system for letting things know when a turn has passed

### PR DESCRIPTION
**Pull request by wynn-rj**
Fixes #108 

Changes proposed in this pull request:
- Creates an observer/subscriber pattern time system that allows objects to subscribe to the time system and get a "notification" when the turn changes
- A prefab that can be added to the strategy map that shows the current turn and provides two ways to increment the turn to the player, an end turn button, as well as the enter button
- The observer has two ways that it can notify a turn has passed, a post turn notification and a pre turn notification. It notifies in the following way: `End Turn Signaled -> Post Turn Notification -> Turn number increased -> Pre Turn Notification`. The idea being that the "turn" is when the player has control and when they press the end button the game gets a chance to do something before the turn ends, and the game gets a chance to do something before the player does on a turn

### CODE REVIEW

**Review by cthomas68 — DISMISSED** [review]
Looks good

**Review by Kuczek8 — DISMISSED** [review]
Looks good

**Review by Kuczek8 — DISMISSED** [review]
looks good

**Review by Toeecko — DISMISSED** [review]

**Review by Toeecko — APPROVED** [review]

**Review by cthomas68 — APPROVED** [review]
w0w

**Pull request merged**
