### PR TITLE
#25 jacks combat branch

### PR DESCRIPTION
**Pull request by Toeecko**
Fixes #ALL .
Changes proposed in this pull request:
-Timebox 
-
-

### CODE REVIEW

**Review by ThBrokenToaster — DISMISSED** [review]
Hell Yeah Brother!

**Review by cthomas68 — COMMENTED** [review]
v nice

**Review by subashch6 — DISMISSED** [review]
yeety

**Review by cthomas68 — DISMISSED** [review]

**Comment by wynn-rj** [comment]
Fixed by recreating dev

**Pull request closed without merging**
